### PR TITLE
Adds grenade selector to CE role

### PR DESCRIPTION
**Pull request by Mallen-git**
adds grenade selector to CE role, also changes how described selectors are handeled to reduce messy code in fn_additems and should allow for easier addition of selectors in the future

### CODE REVIEW

**Review by indig0fox — COMMENTED** [review]
appears okay, assume its tested? i'd like @Mjolnir64 final review + a test session with at least 2 or 3 of us on dedicated before committing

**Comment by Mallen-git** [comment]
> 
> 
> appears okay, assume its tested? i'd like @Mjolnir64 final review + a test session with at least 2 or 3 of us on dedicated before committing

yep, tested on local MP
it is pretty much just a copy paste of the explosive selector script so i cant imagine it'll break anything

**Comment by Mjolnir64** [comment]
I looked through it a bit yesterday, assuming the explosives code works the same, it looks good. Just eschew the changes to the default explosives array (phx_loadout_explosives). The way that was written allows you to only need to change the initial definition to change the default. With the way you've written it, if you wanted to change the default, you would also have to go to a couple other places to make changes and make sure nothing breaks. If you wanted to change the default to an array with multiple explosives, like the selector array, your system will break.

**Comment by Mallen-git** [comment]
> 
> 
> I looked through it a bit yesterday, assuming the explosives code works the same, it looks good. Just eschew the changes to the default explosives array (phx_loadout_explosives). The way that was written allows you to only need to change the initial definition to change the default. With the way you've written it, if you wanted to change the default, you would also have to go to a couple other places to make changes and make sure nothing breaks. If you wanted to change the default to an array with multiple explosives like the explosives selector arrays, your system will break.

yep i didnt see that and that does make more sense, reverting those changes back now

**Review by Mjolnir64 — APPROVED** [review]

**Review by indig0fox — APPROVED** [review]

**Pull request merged**
