### PR TITLE
hotfix week 15

### PR DESCRIPTION
**Pull request by fauxhawkfox**
hotfixed from last release to not break anything and only add/change what's necessary. removes intermediate dev cycle changes that would break release ver

### CODE REVIEW

**Review by fauxhawkfox — COMMENTED** [review]
double checked, appears changes minimized

**Review by Mallen-git — APPROVED** [review]
looks fine, shouldnt break anything obviously

**Comment by Mjolnir64** [comment]
Pushed a commit to this here: https://github.com/Mjolnir64/FNF/pull/47/commits/8c7c0cc8c7e4b9a8ef088934657761a29f385c68

> Previous code would mark anything that inherits from 'buildings' class that is not 'HeliH' subtype, which would end up marking small objects. This checks the size of the bounding sphere of an object to see if it is large enough to deserve a mark. 8 seemed to work well as a min bounding sphere value for an object, but can be changed to include/exclude other objects. Also shortened the function some by adding shared code to in-file function and increased the marker alpha.

**Review by Mallen-git — COMMENTED** [review]
updates look fine and the code changes make it a bit more efficient,
only comment would be by restricting which objects are shown on map its likely fences wont be shown on map which was one of the problems hoping to be solved

**Comment by Mjolnir64** [comment]
Latest version will mark anything that is subtype of 'Buildings' that is not 'Land_DataTerminal_01_F' or subtype of 'Wreck_Base' (vehicle wrecks) and has a bounding sphere value of at least 1.5, which covers fences, walls and other larger objects. I also changed the marker color to match the color already used by the engine to mark buildings.

**Comment by fauxhawkfox** [comment]
We still need to manually include the CUP bridges that are used because they don't inherit from "Buildings".
https://github.com/Mjolnir64/FNF/pull/47/files/6bf5509c337cb3903d63f541e24f99360de73746..1875b8015b682fe8ec6731a41b79385741d0bab9#diff-7ffe30e0dee99f2f629614e59608b98ff170446726cb24ee6317950a0775028fL36

Using black alpha was intentional so it was clear they were custom added. It allows differentiation from vanilla map buildings which is important when mission makers replace existing compounds using Hide Terrain, since we can't hide existing marks.
https://github.com/Mjolnir64/FNF/pull/47/files/6bf5509c337cb3903d63f541e24f99360de73746..1875b8015b682fe8ec6731a41b79385741d0bab9#diff-7ffe30e0dee99f2f629614e59608b98ff170446726cb24ee6317950a0775028fL46-L47

**Comment by Mjolnir64** [comment]
Oh yeah, can change it to 'Static' rather than 'Buildings' which will grab those objects and any others that should be marked but aren't buildings subtype, pretty much everything is sub of static. 

What about black with full alpha, so you don't get much of the bad looking marker overlap, and is distinguishable from the baked terrain markers? That's what looks best, imo. Don't see any reason to go lower than full alpha, just makes it look really ugly.

**Review by fauxhawkfox — COMMENTED** [review]
I'm good w/ pushing this hotfix for use on all missions through the next official release

**Review by Mjolnir64 — APPROVED** [review]

**Pull request merged**
